Redirect to root if search query is empty
oyepriyansh/DevProfiles pull request #260
Opened 2024-09-10 11:02 UTC by YouFoundAlpha

2024-09-10 14:10 UTC, oyepriyansh commented on scripts/app.js
> +const urlParams = new URLSearchParams(window.location.search);
variable `urlParams` is also declared in [another line](https://github.com/oyepriyansh/DevProfiles/blob/9d598168523bfb3e88fd75bd5460f5c620cab0df/scripts/app.js#L147) as const

2024-09-10 14:11 UTC, oyepriyansh requested changes

2024-09-10 14:11 UTC, oyepriyansh commented on scripts/app.js
> +const urlParams = new URLSearchParams(window.location.search);
variable `urlParams` is also declared in [another line](https://github.com/oyepriyansh/DevProfiles/blob/9d598168523bfb3e88fd75bd5460f5c620cab0df/scripts/app.js#L147) as const

2024-09-11 11:37 UTC, oyepriyansh commented
not working

2024-09-11 12:03 UTC, YouFoundAlpha commented
> not working

It works on fine my side 
What's the issue?

2024-09-11 13:26 UTC, merged